# Generated by Django 3.1.2 on 2020-12-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='mivideo.mp4', upload_to='reportes/videos/'),
            preserve_default=False,
        ),
    ]
