# Generated by Django 3.1.2 on 2020-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20201217_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='is_active',
        ),
        migrations.AddField(
            model_name='categoria',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
