# Generated by Django 3.1.2 on 2020-12-12 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporte_video2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='video',
        ),
    ]
