# Generated by Django 3.1.2 on 2020-12-15 21:40

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dimensiones', models.CharField(max_length=100)),
                ('imagen', stdimage.models.StdImageField(blank=True, upload_to='media/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
            },
        ),
    ]
