# Generated by Django 3.1.2 on 2020-12-16 05:03

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickers',
            name='imagen',
            field=stdimage.models.StdImageField(blank=True, upload_to='media/stickers/'),
        ),
    ]
