# Generated by Django 3.1.2 on 2020-10-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to='empresas.direccion'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='empresas.empresa'),
        ),
    ]
