# Generated by Django 3.1.2 on 2020-12-01 21:31

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20201201_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='empresas/logo/'),
        ),
    ]
