# Generated by Django 3.1.2 on 2020-10-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20201017_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=30),
        ),
    ]
