# Generated by Django 3.1.2 on 2020-12-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20201201_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='password',
        ),
    ]
