# Generated by Django 3.1.2 on 2020-10-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20201017_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
