# Generated by Django 3.1.2 on 2020-10-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-id'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
